name: Release PreferencePanes API and Page Assets

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BellCubeDev/update-package-version-by-release-tag@v2
        with: { version: "${{ github.ref_name }}", keep-v: "false", ignore-semver-check: "false" }
      - uses: actions/setup-node@v4
        with: { node-version: "24" }
      - run: npm ci --registry=https://registry.npmjs.org/ --@nsnanocat:registry=https://registry.npmjs.org/
      - run: npx biome format --write package.json
      - run: npm run check && npm run apifox:check
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            dist/api.js
            dist/home.html
            dist/module/index.html
            dist/module/index.mjs
            dist/module/navigation.mjs
